name: tmdb_medallion
version: "1.0.0"
config-version: 2
profile: tmdb_medallion

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  tmdb_medallion:
    silver:
      +schema: silver
      +materialized: table
      +tags: ["silver"]
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
