FROM apache/airflow:2.10.4-python3.11

ARG AIRFLOW_VERSION=2.10.4
ARG PYTHON_VERSION=3.11
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

USER airflow

RUN pip install --no-cache-dir \
      apache-airflow-providers-postgres \
      apache-airflow-providers-amazon \
      --constraint "${CONSTRAINT_URL}"

COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt
